---
"**/*.adoc":
  - indigo423

"opennms-doc/**/*":
  - indigo423

"docs/**/*":
  - indigo423

".circleci/**/*":
  - indigo423
  - mvrueden
  - fooker

".github/**/*":
  - indigo423
  - mvrueden
  - fooker
